### ISSUE TITLE
yt-dlp error

### ISSUE THREAD

**Issue by RikCost** [Epsylon42/mspfa-archive-helper#1]
Need download youtube video in story, i add path to yt-dlp and start that command  
npm start -- --story 31160 --youtubeDownloader C:\mspfa-archive-helper\yt-dlp_win\yt-dlp.exe

and get that error
![image](https://github.com/Epsylon42/mspfa-archive-helper/assets/69048938/909e6218-7e9f-4e79-920e-d1508bd12b10)

$ $'C:\\\\mspfa-archive-helper\\\\yt-dlp_win\\\\yt-dlp.exe' https://www.youtube.com/embed/Ldyeusarzbk -o $'archive/assets/videos/79.%(ext)s'
/bin/bash: line 1: C:\mspfa-archive-helper\yt-dlp_win\yt-dlp.exe: command not found
file:///C:/mspfa-archive-helper/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]: /bin/bash: line 1: C:\mspfa-archive-helper\yt-dlp_win\yt-dlp.exe: command not found
    at fetchYtDlp (file:///C:/mspfa-archive-helper/build/fetch.mjs:151:13)
    exit code: 127 (Command not found)
    at ChildProcess.<anonymous> (file:///C:/mspfa-archive-helper/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 127,
  _signal: null,
  _stdout: '',
  _stderr: '/bin/bash: line 1: C:\\mspfa-archive-helper\\yt-dlp_win\\yt-dlp.exe: command not found\n',
  _combined: '/bin/bash: line 1: C:\\mspfa-archive-helper\\yt-dlp_win\\yt-dlp.exe: command not found\n'
}

Than i try just npm start -- --story 31160
i get this 
![image](https://github.com/Epsylon42/mspfa-archive-helper/assets/69048938/ca9780bc-7d01-4dd9-8485-160db87d36c0)

**Comment by Epsylon42** [comment]
Currently mspfa-archive-helper runs yt-dlp using zx, which seems to be causing the problem on windows. Can probably be fixed by switching to a purpose-made wrapper library like [microlinkhq/youtube-dl-exec](https://github.com/microlinkhq/youtube-dl-exec)

---

Meanwhile, you can try running it in WSL. It should work there.

If that's not an option, here's something that also _might_ help. The problem seems related to google/zx#570, which lists a possible solution.
You might try it yourself by adding this code at the beginning of `src/index.mts`, and rebuilding:
```js
import { $ } from 'zx';
$.shell = 'powershell.exe';
$.prefix = '';
```
